---
title: "Places to Find Data"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Search Engines
* [Data.gov](http://data.gov)  
* [Healthdata.gov](https://www.healthdata.gov/)  
* [World Health Organization Data Repository](http://www.who.int/gho/database/en/)  
* [Temperate Reefbase](http://temperatereefbase.imas.utas.edu.au/)  
* [Data Dryad](http://datadryad.org/)  
* [Dataportals.org](http://dataportals.org/)  
* [World Bank Datasets](https://data.worldbank.org/products/tools)  
* [Data One](https://www.dataone.org/)  
* [Knowledge Network for Biocomplexity](https://knb.ecoinformatics.org/)  
* [Registry of Research Data Repositories](https://www.re3data.org/)  
* [Pangea](https://www.pangaea.de/)  

 
## Data Sets
* [City of Boston Data Portal](https://data.boston.gov/)  
* [Massachusetts Ocean Resource Information System](http://maps.massgis.state.ma.us/map_ol/moris.php)  
* [NOAA Fisheries Datasets](https://www.st.nmfs.noaa.gov/appstech/data-portals/index)  
* [Neotoma Paleoecology Database](https://www.neotomadb.org/)  
* [Global Biodiversity Information Facility](https://www.gbif.org/)  
* [CDC Wonder Database](https://wonder.cdc.gov/)  

## Data Sets with R Packages
* [R EBird Interface](https://github.com/ropensci/rebird)  
* [RNOAA interface for NOAA datasets](https://github.com/ropensci/rnoaa)  
* [HAD CRU Global Climatology Data](https://ropensci.github.io/getCRUCLdata/)
* [tidyhydat - historical hydrometric data](https://cran.rstudio.com/web/packages/tidyhydat/vignettes/tidyhydat_an_introduction.html)  
* [US Federal Geospatial Data via FedDat](http://ropensci.github.io/FedData/)  
* [Electronic Health Record Data](https://github.com/ropensci/cleanEHR)  
* [Open Fisheries](https://github.com/ropensci/rfisheries)  
* [Every tropical cyclone since 1998](https://github.com/ropensci/rrricanesdata)  
* [Climate Change, Agriculture, and Food Security (CCAFS) General Circulation Models (GCM) data](https://github.com/ropensci/ccafs)  
* [R Interface for Ocean Biogeographic Information System](https://github.com/iobis/robis)  
* [R Sample Datasets](https://gist.github.com/zross/6f1b1569512be06f5fb571cc425202bc)  
* [Fivethirtyeight - very heterogeneous!](https://cran.r-project.org/web/packages/fivethirtyeight/vignettes/fivethirtyeight.html)  
* [tidycensus](https://walkerke.github.io/tidycensus/) - Interface for US Census data that returns tidy data frames  
* [A Few Biological Marine Timeseries](https://github.com/ropensci/ots)  
* [Interface with PANGEA database](https://github.com/ropensci/pangaear) - many varied datasets  
* [Biodiversity Information Serving Our Nation](https://github.com/ropensci/rbison)  
* [R National Phenology Network interface](https://github.com/ropensci/rnpn) 
* [Weather data from Environment and Climate Change Canada](https://github.com/ropensci/weathercan)  
* [nomisr - Bemographic and Census data from the UK](https://github.com/EvanOdell/nomisr)  
* [fingertipsR - Public heath data from England](https://cran.rstudio.com/web/packages/fingertipsR/) 
* [inat - iNaturalist data access](https://github.com/ropensci/rinat)  
* [rAvis - citizen science bird counts in Spain](https://github.com/ropensci/rAvis)