---
title: "Biol 355/356: Intro to Data Science for Biology"
---

```{r demoplot, fig.align='center', echo=FALSE, fig.height=4, fig.width=6}
#rmarkdown::render_site()
library(ggplot2)
require(stats); require(graphics)
  
ggplot(data = DNase,
       aes(x = conc, y = density, group = Run)) +
  geom_line(color = "grey")+
  geom_point(color = "black") +
  ylab("DNA Optical Density") + xlab("Protein Concentration") +
  ggtitle("Elisa assay of DNase") +
  theme_classic(base_size = 15)
```

**What:** Biol 355 & 356 Section 01  
  
**Instructor:** [Jarrett Byrnes](http://byrneslab.net), PhD.

**Email:** jarrett.byrnes@umb.edu  
  
**Twitter:** [jebyrnes](http://twitter.com/jebyrnes)

**TA:** Troy Richter. 

**Email:** Troy.Richter001@umb.edu

**Where:** Blue Lab, Healey Library (up one floor)

**Lecture Playlist** Coming Soon

**Zoom Link if you Cannot Be In Person** https://umassboston.zoom.us/j/94809395440 (note, waiting room)  

**Weekly Schedule:** Tuesday & Thursday 2:00-3:15, Lab Friday 10:00 - 1:00  

**Student Hours:** Prof. Byrnes will hold student office hours Tuesday and Thursday from 10-12 in 3130 in the ISC or by appointment.

&nbsp; &nbsp; TA Richter  will hold student office hours Monday from 2-4 in ISC 5210 or by appointment.   

**Syllabi:** [lecture](https://docs.google.com/document/d/1-jW63ua7hVZI52ZzqZnaf8lIfFvIhHLPmdoU6dGyIxQ/edit?usp=sharing) and [lab](https://docs.google.com/document/d/1WSyOwxDmcU8LfmkL-91GKwPBFMZp5OP5X_EookCZ0vk/edit?usp=sharing) - note, this might be out of date relative to the website, and as such, see the [schedule](schedule.html) or other links above.  
  
**Source for this Website:** https://github.com/biol355/biol355.github.io/
&nbsp;  
&nbsp;  
&nbsp;  

## Course News:  

*1/23/2023*  Please join our class slack channel on the UMass Boston R User Group Slack by going to http://umbrug.slack.com, and, once joined, join the #biol355 channel.  

*1/23/2023*  Welcome to the class! Please browse around the site and look at the [lecture syllabus](https://docs.google.com/document/d/1-jW63ua7hVZI52ZzqZnaf8lIfFvIhHLPmdoU6dGyIxQ/edit?usp=sharing) and [lab syllabus](https://docs.google.com/document/d/1WSyOwxDmcU8LfmkL-91GKwPBFMZp5OP5X_EookCZ0vk/edit?usp=sharing)!  

*1/23/2023* Check out previous year's past projects right [here](./past_projects.html)  


