---
title: "data vis with ggplot2"
author: "Jillian Dunic"
date: "February 17, 2016"
output: html_document
---

Let's start by loading our data in

```{r}
library(readxl)

plankton <- read_excel("Data/EST-PR-PlanktonChemTax.xls", sheet = 2)

warnings()

str(plankton)
```

Now that we've loaded in the data, let's look at the column SampleType

```{r}
unique(plankton$SampleType)
```


```{r}
# Double vs single quotes doesn't matter
install.packages("dplyr")
install.packages('ggplot2')
```

Replace the funky values that spaces in them

```{r}
library(dplyr)
plankton <- 
  plankton %>% 
  mutate(SampleType = replace(SampleType, SampleType == 'Whole water', 'Wholewater')) %>% 
  mutate(SampleType = replace(SampleType, SampleType == '<20' | SampleType == "< 20 um", "<20um"))

unique(plankton$SampleType)
```

```{r}
plankton_sub <- plankton[1:164, ]

str(plankton_sub)
```

Plot time!!!!!

```{r}
library(ggplot2)
```

Our first scatterplot

```{r}
ggplot(data = plankton_sub, aes(x = Date, y = TotalChlA)) +
  geom_point()

ggplot(data = plankton_sub) +
  geom_point(aes(x = Date, y = TotalChlA))

```

Now let's add some colour!
```{r}
ggplot(data = plankton_sub, aes(x = Date, y = TotalChlA)) +
  geom_point(colour = 'red')

ggplot(data = plankton_sub, aes(x = Date,  y = TotalChlA, colour = Site)) +
  geom_point()
```

```{r}
ggplot(data = plankton_sub, aes(x = Date, y = TotalChlA)) +
  geom_point(shape = 17, size = 3)
```

Layering

```{r}
ggplot(data = plankton_sub, aes(x = Date, y = TotalChlA, colour = Site, by = Site)) + 
  geom_point() +
  geom_line()

# What happens when we take 'by =' away?
ggplot(data = plankton_sub, aes(x = Date, y = TotalChlA, by = Site)) + 
  geom_point() +
  geom_line()

ggplot(data = plankton_sub, aes(x = Date, y = TotalChlA, colour = Site)) + 
  geom_point(colour = 'black') +
  geom_line()


ggplot(data = plankton_sub, aes(x = Date, y = TotalChlA, colour = Site)) + 
  geom_line() +
  geom_point(colour = 'black')
  
```

```{r}
ggplot(data = plankton_sub, aes(x = Date, y = TotalChlA, colour = Salinity, by = Site)) + 
  geom_line() +
  geom_point(colour = 'black') +
  scale_colour_gradient(low = 'red', high = 'yellow')

```

```{r}
ggplot(data = plankton_sub, aes(x = Temp, y = TotalChlA, colour = Salinity)) +
  geom_point() +
  facet_wrap( ~ SampleType)

```



